/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamenTeoricoRouteImport } from './routes/examen-teorico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PromosRouteImport } from './routes/promos'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenTeoricoRoute = ExamenTeoricoRouteImport.update({
  id: '/examen-teorico',
  path: '/examen-teorico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosRoute = PromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/admin/promos',
  path: '/admin/promos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examen-teorico': typeof ExamenTeoricoRoute
  '/login': typeof LoginRoute
  '/promos': typeof PromosRoute
  '/admin/promos': typeof AdminPromosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examen-teorico': typeof ExamenTeoricoRoute
  '/login': typeof LoginRoute
  '/promos': typeof PromosRoute
  '/admin/promos': typeof AdminPromosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examen-teorico': typeof ExamenTeoricoRoute
  '/login': typeof LoginRoute
  '/promos': typeof PromosRoute
  '/admin/promos': typeof AdminPromosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examen-teorico' | '/login' | '/promos' | '/admin/promos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examen-teorico' | '/login' | '/promos' | '/admin/promos'
  id:
    | '__root__'
    | '/'
    | '/examen-teorico'
    | '/login'
    | '/promos'
    | '/admin/promos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamenTeoricoRoute: typeof ExamenTeoricoRoute
  LoginRoute: typeof LoginRoute
  PromosRoute: typeof PromosRoute
  AdminPromosRoute: typeof AdminPromosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen-teorico': {
      id: '/examen-teorico'
      path: '/examen-teorico'
      fullPath: '/examen-teorico'
      preLoaderRoute: typeof ExamenTeoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promos': {
      id: '/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/admin/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamenTeoricoRoute: ExamenTeoricoRoute,
  LoginRoute: LoginRoute,
  PromosRoute: PromosRoute,
  AdminPromosRoute: AdminPromosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
